### ISSUE TITLE
Change `Hx.push-url` attribute value to `bool`

### ISSUE THREAD

**Issue by mirovarga** [yawaramin/dream-html#11]
It would be nice to be able to specify a `bool` value for the `Hx.push_url` attribute instead of a `string`, as it's actually a boolean value in [htmx](https://htmx.org/docs/#history).

**Comment by yawaramin** [comment]
Hi, according to the reference, this attribute also accepts a URL as its value: https://htmx.org/attributes/hx-push-url/

**Comment by mirovarga** [comment]
Hi, you are right, my bad, I didn't read the reference.

**Comment by yawaramin** [comment]
No prob! Thanks for looking into it.
