### ISSUE TITLE
Ampersand in URI attr not escaped

### ISSUE THREAD

**Issue by jonsterling** [yawaramin/dream-html#20]
I have the following definition:

```
let href fmt = uri_attr "f:href" fmt
```

Later on, `href` is called with a URL that has an ampersand in it. When this is rendered to a string, the ampersand remains and is printed as `&` rather than as `&amp;`. Can you help me figure out what is going on?

**Comment by yawaramin** [comment]
`uri_attr` uses `Uri.to_string` under the hood: https://github.com/yawaramin/dream-html/blob/59be8c503f0ccf57a5a8efca016b7f1da9ff6ed9/lib/dream_html.ml#L121

`Uri.to_string` does percent-encoding of URIs: https://github.com/mirage/ocaml-uri/blob/60fce85fdd6c5e388e088de224557dedf078a248/lib/uri.ml#L611

In a canonical string encoding of a URI, ampersand character is allowed as a separator for query parameters. Ampersand is escaped in HTML text nodes. For example:

```
# open Dream_html;;
# open HTML;;
# #install_printer pp;;
# a [href "/foo?a=1&b=2"] [txt "hello"];;
- : node = <a href="/foo?a=1&b=2">hello</a>

# txt "a & b";;
- : node = a &amp; b
```

**Comment by jonsterling** [comment]
@yawaramin The problem is that I am trying to generate valid XML, and this is not valid XML. Special characters, including ampersands, must be entity-encoded in XML (as well as in HTML 4.1). I understand that this is the original goal of dream-html, but as valid XML is also valid HTML, it might be a good goal.
