### ISSUE TITLE
Spurious whitespace generated

### ISSUE THREAD

**Issue by jonsterling** [yawaramin/dream-html#21]
In the [implementation of `write_tag`](https://github.com/yawaramin/dream-html/blob/59be8c503f0ccf57a5a8efca016b7f1da9ff6ed9/lib/dream_html.ml#L64), a newline is inserted after every closing tag. Unfortunately, this causes incorrect outputs when there are tags interspersed with text. For example, it does not seem possible to generate the following HTML:

```html
<b>Hello</b>, world!
```

The closest we can get is the following, where there is a spurious newline:

```html
<b>Hello</b>
, world!
```

Naturally, the latter renders in the browser as “**Hello** , world” where there is a space before the comma.

Would you accept a PR that removes this newline from `write_tag`? Or is there some other way that I can solve this? thanks!

**Comment by yawaramin** [comment]
Hi, let me know if you want to test it out first and come across any issues; either way planning to cut a release by this weekend. Thanks.
