### ISSUE TITLE
XML-friendly rendering of self-closing / void tags 

### ISSUE THREAD

**Issue by jonsterling** [yawaramin/dream-html#22]
Please feel free to close this if you think it's incompatible with the goals of `dream-html` — but it would be amazing if we could have the void tags formatted as `<tag/>` instead of `<tag>`; this makes it easier for me to produce valid XML, and it also makes it possible for the output of `dream-html` to be parsed by standard XML parsers.

**Comment by yawaramin** [comment]
How about this:

```
# print_endline (to_xml_string (img [src "/foo"]));;
<img
src="/foo" />
- : unit = ()
```

**Comment by jonsterling** [comment]
That would work well for me! Especially if I can have a version that takes a formatter :)

**Comment by yawaramin** [comment]
That's doable. I'll push that later today.

**Comment by yawaramin** [comment]
https://github.com/yawaramin/dream-html/commit/567005e16de920a1a2eabd6342762c74e8f138cb
