### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by yawaramin** [yawaramin/dream-html#25]
Add `index.html` in `gh-pages` branch to deploy to GitHub Pages. Static page with JavaScript to convert from HTML markup to dream-html DSL (the same converter from the bookmarklet). Update the code on the left in real-time as the user changes the HTML on the right.

Sketch:

![dream-html sketch](https://github.com/yawaramin/dream-html/assets/6997/4ed3fb9f-2d47-4d30-b408-8bf078e48761)

Star button:

```html
<!-- Place this tag where you want the button to render. -->
<a class="github-button" href="https://github.com/yawaramin/dream-html" data-color-scheme="no-preference: light; light: light; dark: dark;" data-size="large" data-show-count="true" aria-label="Star yawaramin/dream-html on GitHub">Star</a>

<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
```

Code highlighting: https://highlightjs.org/

**Comment by bromanko** [comment]
Have you considered including a cli to convert HTML to dream-html? I'm probably overcomplicating things but if the conversion logic was in OCaml the JS for use in the bookmarklet and this page could be compiled via ReScript.

**Comment by yawaramin** [comment]
I think doing it inside the browser is the best approach, because that's where people will be viewing the HTML as rendered pages as well as code snippets. Currently I have a bookmarklet for it, which works fine as long as your entire page is the code snippet you want to convert; but adding the converter in the landing page will serve a two-fold purpose--(1) provide a converter for code snippets, and (2) be a nice demo that people will find immediately on landing.
