### ISSUE TITLE
Decouple from Dream library?

### ISSUE THREAD

**Issue by jonsterling** [yawaramin/dream-html#28]
I noticed that almost the entire `dream-html` code does not depend on the `dream` library at all. I am trying to audit my dependencies, and `dream` is one of the biggest sources of dependency bloat in my code. Would you potentially consider a version of `dream-html` that contains just the functionality that can be implemented without `dream`? The only things that would have to be removed are:

- `respond`
- `send`
- `write` 
- `Livereload.route`
- `csrf_tag`

**Comment by jonsterling** [comment]
I'm vendoring the main parts of `dream-html` in Forester, which is working great — would be happy to assist if you think the decoupling is a good idea. We'd have to think a bit about how to incorporate the features that _do_ depend on dream, which look pretty useful.

**Comment by yawaramin** [comment]
Yeah I think we can do this while still keeping everything in this repo. Should be somewhat similar to what I'm doing in https://github.com/yawaramin/fun-sql

Let me look into this and get back to you.
