### ISSUE TITLE
QUESTION: How to pass variables to attributes?

### ISSUE THREAD

**Issue by olgam4** [yawaramin/dream-html#7]
It seem dumb, but I cannot seem to understand how to pass variables to attributes.

I would like to do something like 

```ocaml
    Tag.input [id "input"; name "input"; value input]
```

<img width="776" alt="Screenshot 2023-07-04 at 2 12 08 PM" src="https://github.com/yawaramin/dream-html/assets/31936427/b7c1c493-35c2-41f8-a845-5bfa4c18007f">

I'm sorry to ask such questions that might seem dumb, I'm starting my OCaml journey, as you know.

**Comment by yawaramin** [comment]
All the attributes take format strings as arguments, so you would do e.g. `value "%s" input` (assuming `input` is a `string`). You can refer to the [Printf](https://v2.ocaml.org/api/Printf.html) module for the other flags.

**Comment by olgam4** [comment]
Thanks a lot! :D You are amazing.
