### ISSUE TITLE
use from other web frameworks

### ISSUE THREAD

**Issue by joprice** [yawaramin/dream-html#8]
Hi! I really like this project, but I'm currently testing out piaf. I forked the code and removed the dream dependency, and found I only had to inline a few functions to make it standalone. Could it be split into two opam files, core and dream? That way, it could be reused in projects using cohttp, piaf, etc.

**Comment by yawaramin** [comment]
Hi, that's an interesting idea but I'm not sure at the moment. As you say, it seems to be relatively simple to factor out the Dream-specific parts and leave only a general-purpose HTML eDSL. Could you publish that version somewhere, maybe as a gist, so I can take a look? Want to check it out and think about it a bit.

**Comment by joprice** [comment]
Sure, here is the branch I'm working off of: https://github.com/yawaramin/dream-html/compare/main...joprice:removeDream?expand=1

**Comment by yawaramin** [comment]
Thought about this. IMHO sticking with Dream will be the best option for me personally. I think that Dream will migrate to Eio (or some equivalent) in the future and become even easier to use. I like the idea of sticking with a stable approach.

**Comment by yawaramin** [comment]
Actually did this now! #28
